import json
from pathlib import Path

from shared_config import load_deploy_config


PROJECT_ROOT = Path(__file__).resolve().parent.parent
RUNTIME_CONFIG_PATH = PROJECT_ROOT / "js" / "runtime-config.js"


def main():
    deploy = load_deploy_config(
        required_keys=[
            "CLIENT_BACKEND_URL",
            "CLIENT_BACKEND_WS_URL",
        ]
    )
    payload = {
        "backendUrl": deploy.get("CLIENT_BACKEND_URL"),
        "backendWsUrl": deploy.get("CLIENT_BACKEND_WS_URL"),
    }
    content = (
        "// Auto-generated by scripts/generate_runtime_config.py\n"
        f"window.RUNTIME_CONFIG = {json.dumps(payload, indent=2)};\n"
    )
    RUNTIME_CONFIG_PATH.write_text(content, encoding="utf-8")
    print(f"runtime config written to {RUNTIME_CONFIG_PATH}")


if __name__ == "__main__":
    main()
